<?php
require_once __DIR__ . '/../config/conexion.php';
$db = (new Conexion())->conn;
$ventas = [];
$totales = ['count'=>0,'total'=>0];
$hasSales = (bool)$db->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='ventas'")->fetchColumn();
if ($hasSales) {
    $totales = $db->query("SELECT COUNT(*) AS count, COALESCE(SUM(CASE WHEN estado <> 'Cancelada' THEN total ELSE 0 END),0) AS total FROM ventas")->fetch(PDO::FETCH_ASSOC);
    $ventas = $db->query("SELECT DATE(fecha_venta) AS fecha, COUNT(*) AS cantidad, SUM(total) AS total FROM ventas GROUP BY DATE(fecha_venta) ORDER BY fecha DESC LIMIT 30")->fetchAll(PDO::FETCH_ASSOC);
}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reportes | C&M</title><link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"><link href="css/styles.css" rel="stylesheet"><script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"></script></head><body class="sb-nav-fixed"><nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark"><a class="navbar-brand ps-3" href="index.php?action=gerente">C&M ABRASIVAS</a><a class="nav-link text-white ms-auto me-4" href="index.php?action=logout"><i class="fas fa-sign-out-alt"></i> Cerrar sesión</a></nav><div id="layoutSidenav"><div id="layoutSidenav_nav"><nav class="sb-sidenav sb-sidenav-dark"><div class="sb-sidenav-menu"><div class="nav"><div class="sb-sidenav-menu-heading">Menú principal</div><a class="nav-link" href="index.php?action=gerente"><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>Dashboard</a><a class="nav-link" href="index.php?action=inventario"><div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>Inventario</a><a class="nav-link active" href="index.php?action=reportes"><div class="sb-nav-link-icon"><i class="fas fa-chart-line"></i></div>Reportes</a></div></div><div class="sb-sidenav-footer">C&M Soluciones Abrasivas</div></nav></div><div id="layoutSidenav_content"><main><div class="container-fluid px-4"><h1 class="mt-4">Reportes</h1><ol class="breadcrumb mb-4"><li class="breadcrumb-item active">Resumen de ventas registrado en MySQL</li></ol><div class="row"><div class="col-xl-3 col-md-6"><div class="card bg-primary text-white mb-4"><div class="card-body"><div class="small text-white-50">Ventas registradas</div><div class="fs-4 fw-bold"><?php echo (int)$totales['count']; ?></div></div></div></div><div class="col-xl-3 col-md-6"><div class="card bg-success text-white mb-4"><div class="card-body"><div class="small text-white-50">Total vendido</div><div class="fs-4 fw-bold">$ <?php echo number_format((float)$totales['total'],0,',','.'); ?></div></div></div></div></div><div class="card mb-4"><div class="card-header"><i class="fas fa-chart-line me-1"></i> Ventas por día</div><div class="card-body table-responsive"><table class="table table-striped"><thead><tr><th>Fecha</th><th>Cantidad</th><th>Total</th></tr></thead><tbody><?php foreach($ventas as $venta): ?><tr><td><?php echo htmlspecialchars($venta['fecha'],ENT_QUOTES,'UTF-8'); ?></td><td><?php echo (int)$venta['cantidad']; ?></td><td>$ <?php echo number_format((float)$venta['total'],0,',','.'); ?></td></tr><?php endforeach; ?><?php if(!$ventas): ?><tr><td colspan="3" class="text-center text-muted">No hay ventas registradas.</td></tr><?php endif; ?></tbody></table></div></div></div></main></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script><script src="js/scripts.js"></script></body></html>
